"""Initial migration

Revision ID: 4cb402362ad5
Revises: 
Create Date: 2023-08-03 23:15:19.951417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb402362ad5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('intentid', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['intentid'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('intentid', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['intentid'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('locationId', sa.String(), nullable=False),
    sa.Column('user_input', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['locationId'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(precision=2), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('locationId', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['locationId'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qrs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('locationId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['locationId'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_tags')
    op.drop_table('qrs')
    op.drop_table('items')
    op.drop_table('chatbots')
    op.drop_table('responses')
    op.drop_table('patterns')
    op.drop_table('locations')
    op.drop_table('category_tags')
    op.drop_table('tags')
    op.drop_table('organizations')
    op.drop_table('intents')
    op.drop_table('categories')
    # ### end Alembic commands ###
